### ISSUE TITLE
English Language

### ISSUE THREAD

**Issue by Nothoro** [xiaoyaocode163/VisualFreeBasic#1]
I really like this editor. However even though I set the IDE to English, It still displays Chinese, and I cannot read it.
![ICantReadThese](https://user-images.githubusercontent.com/48295093/107554085-4e678c80-6b8a-11eb-8dbf-55dfa6df5500.jpg)

http://69.170.216.5/cantreadit.jpg

If there is any way that I can help, please inform me. I would be happy to try.

**Comment by ghost** [comment]
The author has a negative attitude towards adding translations.
原作者对于添加翻译这件事持消极态度。
![image](https://user-images.githubusercontent.com/42790878/135582770-4e149a84-1c38-4677-bba3-59139554b143.png)
I am communicating with the author, hoping to get better translation support.
我正在与作者沟通，以期望能获得更好的翻译支持。

**Comment by xiaoyaocode163** [comment]
> I really like this editor. However even though I set the IDE to English, It still displays Chinese, and I cannot read it.
> ![ICantReadThese](https://user-images.githubusercontent.com/48295093/107554085-4e678c80-6b8a-11eb-8dbf-55dfa6df5500.jpg)
> 
> http://69.170.216.5/cantreadit.jpg
> 
> If there is any way that I can help, please inform me. I would be happy to try.

The English version is being optimized and upgraded, and the workload is heavy. On April 24, 2021, the English version has made many improvements, but there are still many Chinese characters. Please be patient

**Comment by xiaoyaocode163** [comment]
> 笔者有对加翻译否定态度。
> 原作者对于添加翻译这件事持消极态度。
> 我与作者沟通，希望能得到更好的翻译支持。
> 我正在与作者沟通，以期望能获得更好的翻译支持。



> The author has a negative attitude towards adding translations.
> 原作者对于添加翻译这件事持消极态度。
> I am communicating with the author, hoping to get better translation support.
> 我正在与作者沟通，以期望能获得更好的翻译支持。

It is not easy to develop the entire IDE by one person, and the translation workload is also very large. It would be nice if the Chinese and English versions were developed together 6 years ago. After 2,000 days, there are still almost no users in 10 other countries around the world. In fact, VB6 has more users in countries other than China

**Comment by sokinkeso** [comment]
Visual Freebasic is a really awesome IDE!!!
Congratulations to the author!!!
I have started translating (with google translate) a lot of files (controls, events, inc files, help.db), but i cannot find were are the text for the main window left pane..can anyone help?
![vfb1](https://user-images.githubusercontent.com/113173954/234887036-d4c93000-324b-4998-b0d6-0e8281f335d0.png)
![vfb2](https://user-images.githubusercontent.com/113173954/234887047-a0ca10c7-c98c-4bbf-8bf2-4b54280ffbc6.png)
![vfb3](https://user-images.githubusercontent.com/113173954/234887055-951cee9f-a7aa-494c-8590-f4724530fa33.png)

**Comment by xiaoyaocode163** [comment]
maybe in sqlite db file.if you can register a QQ NUMBER,it's will fine




QQ GROUP:78458582




https://im.qq.com/index/#downloadAnchor

At 2023-04-27 21:42:53, "Nikos Kesoglidis" ***@***.***> wrote:

I have started translating (with google translate) a lot of files (controls, events, inc files, help.db), but i cannot find were are the text for the main window..can anyone help?

**Comment by sokinkeso** [comment]
> 

Thank you very much for the reply. I have already searched in the sq3lite db file, and could not find these strings..
Is it possible that these texts are hardcoded?
I have done a lot of translation so far...
I will try to register QQ, and send you from there a link to download the English  translated version I have made.

**Comment by sokinkeso** [comment]
> maybe in sqlite db file.if you can register a QQ NUMBER,it's will fine QQ GROUP:78458582 https://im.qq.com/index/#downloadAnchor At 2023-04-27 21:42:53, "Nikos Kesoglidis" ***@***.***> wrote: I have started translating (with google translate) a lot of files (controls, events, inc files, help.db), but i cannot find were are the text for the main window..can anyone help? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Hi again, I cannot register in QQ from PC (where I can translate the text), and the android app is in Chinese...
Is there any other way to communicate with you?
An email maybe?

**Comment by xiaoyaocode163** [comment]
if you have many idea or question,If you have a lot of questions or creative ideas, you can often chat on QQ. If you search for QQ in the Apple APP Store, there should be an English version of the app




***@***.***

At 2023-05-04 19:14:22, "Nikos Kesoglidis" ***@***.***> wrote:

maybe in sqlite db file.if you can register a QQ NUMBER,it's will fine QQ GROUP:78458582 https://im.qq.com/index/#downloadAnchor At 2023-04-27 21:42:53, "Nikos Kesoglidis" @.> wrote: I have started translating (with google translate) a lot of files (controls, events, inc files, help.db), but i cannot find were are the text for the main window..can anyone help? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

Hi again, I cannot register in QQ from PC (where I can translate the text), and the android app is in Chinese...
Is there any other way to communicate with you?
An email maybe?
