### ISSUE TITLE
Filenames does not work outside china

### ISSUE THREAD

**Issue by rexxitall** [xiaoyaocode163/VisualFreeBasic#3]
Most of the filenames used contains chinese  Unicode chars !!!
Which will be converted later on to chars which can not be handled anymore by the 
Which are translated to chars which will collide with the naming rules of a western Windows filesystem.
Filenames should not contain ANY characters higher then ascii code 127 ! Should not contain any whitechars and so on. Especially chars which are used by the OS for special purposes are totally forbidden. like those --->*, ?, | ,\ ,: ...
0..9, abc... z, ABC...Z, _- are fine Same rules like FBC Variable names...

The OS will NOT be able to handle files which contain those in the name. You can not even delete them ! To fix my Harddrive i will have to start a Unix or use a file tool and rename them back until i can delete them. I understand why someones has used chinese characters. But that will mix up everything outside China. And does not make a good karma at the moment - at least not by me :) It would be very sad if the fine work so far i could see is just available by chinese peoples. Especially cause the hard work and underlaying compilers are not made in china. So please be fair and fix it :)

![image](https://user-images.githubusercontent.com/22050310/121390679-e6655f00-c94d-11eb-8169-a77321f655b3.png)
![image](https://user-images.githubusercontent.com/22050310/121390823-0bf26880-c94e-11eb-9abf-85bb5d6f9830.png)

**Comment by ghost** [comment]
My bad.
I did not upload the latest version in time
Now this problem has been solved in the new version
![Snipaste_2021-07-08_10-27-17.png](https://i.loli.net/2021/07/08/U3Cx2Y5cIgBuMR9.png)
[download](https://drive.google.com/drive/folders/1HgpnHn6dNhbtBlHM0PPK9VNJVGt5V5K0?usp=sharing).

Chinese Notes have not been translated

**Comment by xiaoyaocode163** [comment]
> Most of the filenames used contains chinese Unicode chars !!! Which will be converted later on to chars which can not be handled anymore by the Which are translated to chars which will collide with the naming rules of a western Windows filesystem. Filenames should not contain ANY characters higher then ascii code 127 ! Should not contain any whitechars and so on. Especially chars which are used by the OS for special purposes are totally forbidden. like those --->*, ?, | ,\ ,: ... 0..9, abc... z, ABC...Z, _- are fine Same rules like FBC Variable names...
> 
> The OS will NOT be able to handle files which contain those in the name. You can not even delete them ! To fix my Harddrive i will have to start a Unix or use a file tool and rename them back until i can delete them. I understand why someones has used chinese characters. But that will mix up everything outside China. And does not make a good karma at the moment - at least not by me :) It would be very sad if the fine work so far i could see is just available by chinese peoples. Especially cause the hard work and underlaying compilers are not made in china. So please be fair and fix it :)
> 
> ![image](https://user-images.githubusercontent.com/22050310/121390679-e6655f00-c94d-11eb-8169-a77321f655b3.png) ![image](https://user-images.githubusercontent.com/22050310/121390823-0bf26880-c94e-11eb-9abf-85bb5d6f9830.png)

you can download new version test
