### ISSUE TITLE
About Chinese code hints and documents

### ISSUE THREAD

**Issue by ghost** [xiaoyaocode163/VisualFreeBasic#4]
I will replace the basic Chinese document with English
It takes a long time, because the original author doesn’t know how to do it, and, obviously, he doesn’t understand English ***very well***.
ㄟ( ▔, ▔ )ㄏ

**Comment by hlizard** [comment]
你要高调做事也可以, 但请不要再贬低别人!

**Comment by ghost** [comment]
> 你要高调做事也可以, 但请不要再贬低别人!

笑死，这是他自己在群里说的，他不懂英文，他没上过高中（还是初中来着不记得了）
我翻译他自己写的文档的时候还得改一堆错字和不太规范的方言化表达 

他人就在群里，你自己去问❤
