### ISSUE TITLE
ComManager.dll contains trojan

### ISSUE THREAD

**Issue by Build-0-Matic** [xiaoyaocode163/VisualFreeBasic#8]
Upon starting the program, my antivirus told me that ComManager.dll contains a backdoor trojan.
I sent the file to virustotal, and 26 different antivirus come to the same conclusion.

Please resolve problem.

**Comment by xiaoyaocode163** [comment]
upload new version 5.8.11
https://www.freebasic.net/forum/viewtopic.php?t=28522
talk here
